[package]
name = "flakec-backend"
version = "0.0.0"
edition = "2021"


[dependencies.lexer]
package = "flakec-lexer"
path = "../flakec-lexer"
features = ["flakec_dep_of_compiler","use_const"]


[features]
flakec_dep_of_compiler = []