//! Flakec Lexer
//!
//! The Lexer is automatically generated by [lexgen].

#![feature(adt_const_params, vec_into_raw_parts)]

use keyword::Keyword;
use literal::Literal;

pub mod keyword;
pub mod literal;
pub mod span;
pub mod stream;
pub mod syn;
pub mod token;




pub use syn::Lexer;

#[cfg(test)]
mod tests {
    use crate::Lexer;

    #[test]
    pub fn test() {
        let mut lexer = Lexer::new(include_str!("../test.fl"));

        panic!("{:?}", lexer.next());
    }
}
