[package]
name = "flakec-lexer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexgen = "0.15.0"
lexgen_util = "*"

[features]
flakec_dep_of_compiler = []
use_const = []